<!DOCTYPE html>
<html lang="es">
<head>
    <?php include('partial_views/head_tag.php') ?>
</head>
<body>
    <?php include('partial_views/navbar.php') ?>
    <div class="main-wrapper terms-wrapper">
        <div class="gmw">
            <div class="main-title-underline">
                <h1>Términos y condiciones</h1>
                <div class="divisor"></div>
            </div>

            <h2 class="mt-4">Lorem, ipsum dolor sit</h2>
            <p class="mt-1">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed nisi ut metus suscipit tincidunt in non ante. In commodo dolor quis purus condimentum rutrum. Pellentesque a diam et nibh sodales vehicula nec id urna. Curabitur a magna nisi. Suspendisse potenti. Ut malesuada urna dapibus maximus pharetra. Duis sed est laoreet, bibendum ligula non, suscipit neque. Duis vitae nunc risus. Vestibulum vehicula dictum libero non scelerisque. Sed tincidunt lacinia ex, sit amet volutpat mauris. Ut et mollis orci, sed sodales augue. Nullam viverra, mi id interdum malesuada, erat sem facilisis dolor, vel gravida magna metus at nunc. Donec sed viverra velit. Sed fermentum sem dui, eu volutpat dolor ultrices eget. Vestibulum enim enim, imperdiet in ligula sed, iaculis congue purus. Duis vehicula turpis vitae elit faucibus, sed convallis velit aliquet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed nisi ut metus suscipit tincidunt in non ante. In commodo dolor quis purus condimentum rutrum. Pellentesque a diam et nibh sodales vehicula nec id urna.<br><br>Curabitur a magna nisi. Suspendisse potenti. Ut malesuada urna dapibus maximus pharetra. Duis sed est laoreet, bibendum ligula non, suscipit neque. Duis vitae nunc risus. Vestibulum vehicula dictum libero non scelerisque. Sed tincidunt lacinia ex, sit amet volutpat mauris. Ut et mollis orci, sed sodales augue. Nullam viverra, mi id interdum malesuada, erat sem facilisis dolor, vel gravida magna metus at nunc. Donec sed viverra velit. Sed fermentum sem dui, eu volutpat dolor ultrices eget. Vestibulum enim enim, imperdiet in ligula sed, iaculis congue purus. Duis vehicula turpis vitae elit faucibus, sed convallis velit aliquet.</p>

            <h2 class="mt-2">Lorem, ipsum dolor sit</h2>
            <p class="mt-1">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed nisi ut metus suscipit tincidunt in non ante. In commodo dolor quis purus condimentum rutrum. Pellentesque a diam et nibh sodales vehicula nec id urna. Curabitur a magna nisi. Suspendisse potenti. Ut malesuada urna dapibus maximus pharetra. Duis sed est laoreet, bibendum ligula non, suscipit neque. Duis vitae nunc risus. Vestibulum vehicula dictum libero non scelerisque. Sed tincidunt lacinia ex, sit amet volutpat mauris. Ut et mollis orci, sed sodales augue. Nullam viverra, mi id interdum malesuada, erat sem facilisis dolor, vel gravida magna metus at nunc. Donec sed viverra velit. Sed fermentum sem dui, eu volutpat dolor ultrices eget. Vestibulum enim enim, imperdiet in ligula sed, iaculis congue purus. Duis vehicula turpis vitae elit faucibus, sed convallis velit aliquet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed nisi ut metus suscipit tincidunt in non ante. In commodo dolor quis purus condimentum rutrum. Pellentesque a diam et nibh sodales vehicula nec id urna.<br><br>Curabitur a magna nisi. Suspendisse potenti. Ut malesuada urna dapibus maximus pharetra. Duis sed est laoreet, bibendum ligula non, suscipit neque. Duis vitae nunc risus. Vestibulum vehicula dictum libero non scelerisque. Sed tincidunt lacinia ex, sit amet volutpat mauris. Ut et mollis orci, sed sodales augue. Nullam viverra, mi id interdum malesuada, erat sem facilisis dolor, vel gravida magna metus at nunc. Donec sed viverra velit. Sed fermentum sem dui, eu volutpat dolor ultrices eget. Vestibulum enim enim, imperdiet in ligula sed, iaculis congue purus. Duis vehicula turpis vitae elit faucibus, sed convallis velit aliquet.</p>

            <h2 class="mt-2">Lorem, ipsum dolor sit</h2>
            <p class="mt-1">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed nisi ut metus suscipit tincidunt in non ante. In commodo dolor quis purus condimentum rutrum. Pellentesque a diam et nibh sodales vehicula nec id urna. Curabitur a magna nisi. Suspendisse potenti. Ut malesuada urna dapibus maximus pharetra. Duis sed est laoreet, bibendum ligula non, suscipit neque. Duis vitae nunc risus. Vestibulum vehicula dictum libero non scelerisque. Sed tincidunt lacinia ex, sit amet volutpat mauris. Ut et mollis orci, sed sodales augue. Nullam viverra, mi id interdum malesuada, erat sem facilisis dolor, vel gravida magna metus at nunc. Donec sed viverra velit. Sed fermentum sem dui, eu volutpat dolor ultrices eget. Vestibulum enim enim, imperdiet in ligula sed, iaculis congue purus. Duis vehicula turpis vitae elit faucibus, sed convallis velit aliquet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed nisi ut metus suscipit tincidunt in non ante. In commodo dolor quis purus condimentum rutrum. Pellentesque a diam et nibh sodales vehicula nec id urna.<br><br>Curabitur a magna nisi. Suspendisse potenti. Ut malesuada urna dapibus maximus pharetra. Duis sed est laoreet, bibendum ligula non, suscipit neque. Duis vitae nunc risus. Vestibulum vehicula dictum libero non scelerisque. Sed tincidunt lacinia ex, sit amet volutpat mauris. Ut et mollis orci, sed sodales augue. Nullam viverra, mi id interdum malesuada, erat sem facilisis dolor, vel gravida magna metus at nunc. Donec sed viverra velit. Sed fermentum sem dui, eu volutpat dolor ultrices eget. Vestibulum enim enim, imperdiet in ligula sed, iaculis congue purus. Duis vehicula turpis vitae elit faucibus, sed convallis velit aliquet.</p>
        </div>
    </div>
    <?php include('partial_views/footer.php') ?>
</body>
</html>